### PR TITLE
Update compute_deviations.py

### PR DESCRIPTION
**Pull request by bensonbits**
I dont know if this is the way to suggest this change. 

on my computer, Bio needs to be bio

### CODE REVIEW

**Comment by bensonbits** [comment]
This also needs change in compute_mean.py

**Comment by ErikPoppleton** [comment]
Thanks for catching that!  What distribution of Biopython are you using?  I've set up the one from Conda on both Windows and Linux at this point and they have always been "Bio"

**Comment by bensonbits** [comment]
Its really strange: i did

conda install -c anaconda biopython

On windows python 3.7

It seems like someone else had a similar problem

https://stackoverflow.com/questions/49848517/biopython-no-module-named-bio

Cheers

Erik b

**Comment by ErikPoppleton** [comment]
Wild... I wonder how many versions this affects.  I just pushed out the fix to all the scripts that use biopython.  Could you do me a favor and run config.py in your environment?  I had to do something a bit more complicated there and I want to make sure that it actually catches the different name.

**Comment by bensonbits** [comment]
Seems to work good, except for DNAtools, don't have oxDNA on this computer.
Biopython seems to be spelled with capital B but only import as "bio" 🙃

INFO: Python version: 3.7.7
INFO: Package Numpy found. Version: 1.18.1
INFO: Package MatPlotLib found. Version: 3.1.3
INFO: Package BioPython found. Version: 1.76
INFO: Package SciKit-Learn found. Version: 0.22.1
INFO: Package Pathos found. Version: 0.2.5
INFO: No dependency issues found.
ERROR: Cannot execute DNAnalysis program. Please edit config.py to point to
your compiled DNAnalysis. Current target:
/home/erik/software/oxdna-code/oxDNA/bin/DNAnalysis

**Comment by ErikPoppleton** [comment]
Perfect, thanks!

**Pull request merged**
